### ISSUE TITLE
Not building on OSX...

### ISSUE THREAD

**Issue by meshula** [glennrp/libpng#100]
At top of tree, CMAKE_OSX_ARCHITECTURES is now resolving to an empty string, yielding a bad clang line as you can see below. The error occurs with both a make generator and the Xcode generator.

I checked out from 830608b, and things build fine from that commit.

-- Build files have been written to: /Users/dp/Projects/stage/prereq/libpng/build
Scanning dependencies of target genfiles
Scanning dependencies of target png-fix-itxt
[  1%] Generating pnglibconf.c
[  4%] Generating pngprefix.h
[  4%] Generating scripts/pnglibconf.c
[  5%] Building C object CMakeFiles/png-fix-itxt.dir/contrib/tools/png-fix-itxt.c.o
[  7%] Generating scripts/symbols.out
[  8%] Linking C executable png-fix-itxt
clang: error: invalid arch name '-arch -isysroot'
clang: warning: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk: 'linker' input unused
CMake Error at scripts/genout.cmake:73 (message):
  Failed to generate
  /Users/dp/Projects/stage/prereq/libpng/build/scripts/symbols.out.tf1

**Comment by glennrp** [comment]
Fixed in libpng-1.6.22

**Comment by meshula** [comment]
Thanks :)
