### ISSUE TITLE
IDAT: invalid distance too far back in recent 1.6 versions

### ISSUE THREAD

**Issue by fdelapena** [glennrp/libpng#125]
Here is an attached PNG file which was loading properly at least with 1.6.18 version. Recent versions (including 1.6.23) return this error.

[test.png.zip](https://github.com/glennrp/libpng/files/361605/test.png.zip)

**Comment by glennrp** [comment]
Here's the relevant changelog entry:

Version 1.6.20rc01 [November 26, 2015]
  Fixed an error in handling of bad zlib CMINFO field in pngfix, found by
    American Fuzzy Lop, reported by Brian Carpenter.  inflate() doesn't
    immediately fault a bad CMINFO field; instead a 'too far back' error
    happens later (at least some times).  pngfix failed to limit CMINFO to
    the allowed values but then assumed that window_bits was in range,
    triggering an assert. The bug is mostly harmless; the PNG file cannot
    be fixed.
