### ISSUE TITLE
Minor finding from static analysis

### ISSUE THREAD

**Issue by irwir** [glennrp/libpng#126]
File _pngrutil.c_ in _libpng16_ branch, lines
3422: `if (png_isaligned(dp, png_uint_32) != 0 &&`
3423: `    png_isaligned(sp, png_uint_32) != 0 &&`
Comparison to zero is not needed, because macro _png_isaligned()_ already gives boolean value  (as in lines 3413 and 3414).

**Comment by glennrp** [comment]
Thanks, I agree.

**Comment by irwir** [comment]
Thanks for your work.
