### ISSUE TITLE
Undefined behaviour in pngrutil.c

### ISSUE THREAD

**Issue by irwir** [glennrp/libpng#149]
Line 423 in libpng16 pngrutil.c is
` if (((png_ptr->options >> PNG_IGNORE_ADLER32) & 3) == PNG_OPTION_ON)`

`png_ptr->options` is `png_byte` and has 8 bits
`PNG_IGNORE_ADLER32` equals 8
C/C++ standards claim that shift by the number of available bits (or more) is an undefined behaviour.

**Comment by glennrp** [comment]
I've pushed a change to the GIT repositories to
change png_ptr->options from a png_byte to a
png_uint_32  See f8bdbd4d8f9da0ed6003ac786db847e9326dd986
