### ISSUE TITLE
Potential arithmetic overflows in libpng16 branch

### ISSUE THREAD

**Issue by boxerab** [glennrp/libpng#153]
Below are warnings from VS 2015 static analyzer.

To fix, for example:

`(png_size_t)(row_width << 3)` can overflow, while 

`((png_size_t)row_width << 3)`  will not overflow.

     \libpng\pngrtran.c(4305): warning C6297: Arithmetic overflow:  32-bit value is shifted, then cast to 64-bit value.  Results might not be an expected value.
    \libpng\pngrtran.c(4466): warning C6297: Arithmetic overflow:  32-bit value is shifted, then cast to 64-bit value.  Results might not be an expected value.
    \libpng\pngrtran.c(4522): warning C6297: Arithmetic overflow:  32-bit value is shifted, then cast to 64-bit value.  Results might not be an expected value.
    \libpng\pngrtran.c(4545): warning C6297: Arithmetic overflow:  32-bit value is shifted, then cast to 64-bit value.  Results might not be an expected value.

**Comment by glennrp** [comment]
Thanks.  Fixed in libpng16 branch of the GIT repos (commit 4f31b7)

**Comment by boxerab** [comment]
Great, thanks for maintaining the excellent library.
