### ISSUE TITLE
Missing zlib dependency

### ISSUE THREAD

**Issue by pneerincx** [glennrp/libpng#167]
Adding "Requires: zlib" to libpng.pc.in like in the patch below solved compilation issues...

diff -ru libpng-1.6.29.original/libpng.pc.in libpng-1.6.29.patched/libpng.pc.in
--- libpng-1.6.29.original/libpng.pc.in	2017-03-16 13:21:02.000000000 +0100
+++ libpng-1.6.29.patched/libpng.pc.in	2017-06-29 11:04:17.000000000 +0200
@@ -6,6 +6,7 @@
 Name: libpng
 Description: Loads and saves PNG files
 Version: @PNGLIB_VERSION@
+Requires: zlib
 Libs: -L${libdir} -lpng@PNGLIB_MAJOR@@PNGLIB_MINOR@
 Libs.private: @LIBS@
 Cflags: -I${includedir}

**Comment by glennrp** [comment]
Thanks.  I pushed your change to the libpng16 branch: commit 89b8c13

**Comment by pneerincx** [comment]
Thanks; looking forward to 1.6.31!
