### ISSUE TITLE
Declaration/definition mismatch for png_set_eXIf_1

### ISSUE THREAD

**Issue by irwir** [glennrp/libpng#171]
File _png.h_, line _2019_
Third paramter has no _const_ for the third parameter in declaration.
Maybe it is not needed at all, and should be removed from the method definintion.

**Comment by glennrp** [comment]
Thanks, fixed in commit 554d4400ab4200075a5e074b6f88aafe783e8e3a

**Comment by irwir** [comment]
The declaration in question starts at line **2019** for the function returning _void_, while the commit changed the line just above for other function returning png_uint_32.

**Comment by glennrp** [comment]
See comit 3a957dd96fa40164da8e64aae800dcbf8c607aad

**Comment by irwir** [comment]
Thanks, the warning is gone now.
