### ISSUE TITLE
Naming convention in `contrib/testpngs/crashers/*`

### ISSUE THREAD

**Issue by ChristopheEcabert** [glennrp/libpng#172]
On OSX, after a fresh clone of the repo, you will end up with changes even though you have not touch anything yet. After some digging it appears that some files have the same names since the file system is case insensitive ([SO](https://stackoverflow.com/a/5022417/4546884)). The files are listed below:

- `contrib/testpngs/crashers/huge_juNK_chunk.png`
- `contrib/testpngs/crashers/huge_juNk_chunk.png`

This might lead to error, when cloned automatically from build script (_i.e. CMake's ExternalProjects_)

Christophe

**Comment by glennrp** [comment]
I will rename one of them, but that's too bad because the names "juNK" and "jUNk" are significantly different to PNG; the case of the chunkname bytes is used to distinguish between various types of chunks.

**Comment by glennrp** [comment]
See commit d19e8b9a4b15311408112482e75d3eef82ece5ba

**Comment by ChristopheEcabert** [comment]
Thanks for the quick fix
