### ISSUE TITLE
Make Failed

### ISSUE THREAD

**Issue by ben29** [glennrp/libpng#173]
> [root@server libpng-1.6.32]# make
> make  all-am
> make[1]: Entering directory `/libpng-1.6.32'
> /bin/sh ./libtool  --tag=CC   --mode=link gcc  -g -O2   -o pngfix contrib/tools/pngfix.o libpng16.la -lm -lz -lm 
> libtool: link: gcc -g -O2 -o .libs/pngfix contrib/tools/pngfix.o  ./.libs/libpng16.so -lz -lm -Wl,-rpath -Wl,/usr/local/lib
> ./.libs/libpng16.so: undefined reference to `inflateValidate'
> collect2: error: ld returned 1 exit status
> make[1]: *** [pngfix] Error 1
> make[1]: Leaving directory `/libpng-1.6.32'
> make: *** [all] Error 2

configure :

`./configure --prefix=/usr/local`

Centos 7

**Comment by glennrp** [comment]
I'm not sure why that is happening sometimes.  It seems that 1.6.32 is looking for zlib-1.2.11

**Comment by glennrp** [comment]
See also issue #155

**Comment by ben29** [comment]
i'm using zlib 1.2.11

**Comment by glennrp** [comment]
Right, but you also seem to have an older zlib somewhere on your system that the linker is finding.

**Comment by ben29** [comment]
i build zlib like this:

>     ./configure  \
>  --prefix=/usr/local;

**Comment by glennrp** [comment]
Try

    ./configure --prefix=/usr/local --zprefix

That changes all the exported symbols in zlib from xxx to z_xxx
which allows your old zlib to coexist with the new one.

**Comment by ben29** [comment]
did you mean like this?

> ./configure --prefix=/usr/local --with-zlib-prefix=/usr/local

**Comment by glennrp** [comment]
No, --with-zlib-prefix=/usr/local places the library in /usr/local which you've already got.
--zprefix renames the exported symbols so they don't conflict with another zlib that is
present, and probably required by other applications, on your system

**Comment by ben29** [comment]
i did:

> ./configure --with-zlib-prefix=/usr/local

results:

> gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT contrib/tools/pngfix.o -MD -MP -MF $depbase.Tpo -c -o contrib/tools/pngfix.o contrib/tools/pngfix.c &&\
> mv -f $depbase.Tpo $depbase.Po
> /bin/sh ./libtool  --tag=CC   --mode=link gcc  -g -O2   -o pngfix contrib/tools/pngfix.o libpng16.la -lm -lz -lm 
> libtool: link: gcc -g -O2 -o .libs/pngfix contrib/tools/pngfix.o  ./.libs/libpng16.so -lz -lm -Wl,-rpath -Wl,/usr/local/lib
> ./.libs/libpng16.so: undefined reference to `inflateValidate'
> collect2: error: ld returned 1 exit status
> make[1]: *** [pngfix] Error 1
> make[1]: Leaving directory `/libpng-1.6.32'
> make: *** [all] Error 2

**Comment by ben29** [comment]
i build the Zlib like this:

> make install
> rm -f /usr/local/lib/libz.a
> cp libz.a /usr/local/lib
> chmod 644 /usr/local/lib/libz.a
> cp libz.so.1.2.11 /usr/local/lib
> chmod 755 /usr/local/lib/libz.so.1.2.11
> rm -f /usr/local/share/man/man3/zlib.3
> cp zlib.3 /usr/local/share/man/man3
> chmod 644 /usr/local/share/man/man3/zlib.3
> rm -f /usr/local/lib/pkgconfig/zlib.pc
> cp zlib.pc /usr/local/lib/pkgconfig
> chmod 644 /usr/local/lib/pkgconfig/zlib.pc
> rm -f /usr/local/include/zlib.h /usr/local/include/zconf.h
> cp zlib.h zconf.h /usr/local/include
> chmod 644 /usr/local/include/zlib.h /usr/local/include/zconf.

**Comment by glennrp** [comment]
It won't solve your problem if you don't use --zprefix.

**Comment by ben29** [comment]
ok i did recompile zlib with:

> ./configure --zprefix --prefix=/usr/local

now the libpng

> ./configure --prefix=/usr/local --with-zlib-prefix=/usr/local

make:

```
contrib/tools/pngfix.o: In function `zlib_advance':
/usr/local/binary/services/libpng-1.6.32/contrib/tools/pngfix.c:2375: undefined reference to `z_inflate'
contrib/tools/pngfix.o: In function `zlib_end':
/usr/local/binary/services/libpng-1.6.32/contrib/tools/pngfix.c:2159: undefined reference to `z_inflateEnd'
contrib/tools/pngfix.o: In function `zlib_init':
/usr/local/binary/services/libpng-1.6.32/contrib/tools/pngfix.c:2230: undefined reference to `z_inflateInit2_'
contrib/tools/pngfix.o: In function `zlib_reset':
/usr/local/binary/services/libpng-1.6.32/contrib/tools/pngfix.c:2184: undefined reference to `z_inflateReset2'
./.libs/libpng16.so: undefined reference to `z_deflateEnd'
./.libs/libpng16.so: undefined reference to `z_crc32'
./.libs/libpng16.so: undefined reference to `z_inflateValidate'
./.libs/libpng16.so: undefined reference to `z_deflateReset'
./.libs/libpng16.so: undefined reference to `z_deflate'
./.libs/libpng16.so: undefined reference to `z_inflateReset'
./.libs/libpng16.so: undefined reference to `z_adler32'
./.libs/libpng16.so: undefined reference to `z_deflateInit2_'
collect2: error: ld returned 1 exit status
make[1]: *** [pngfix] Error 1
make[1]: Leaving directory `/usr/local/binary/services/libpng-1.6.32'
make: *** [all] Error 2

```

make install:

```
contrib/tools/pngfix.o: In function `zlib_advance':
/usr/local/binary/services/libpng-1.6.32/contrib/tools/pngfix.c:2375: undefined reference to `z_inflate'
contrib/tools/pngfix.o: In function `zlib_end':
/usr/local/binary/services/libpng-1.6.32/contrib/tools/pngfix.c:2159: undefined reference to `z_inflateEnd'
contrib/tools/pngfix.o: In function `zlib_init':
/usr/local/binary/services/libpng-1.6.32/contrib/tools/pngfix.c:2230: undefined reference to `z_inflateInit2_'
contrib/tools/pngfix.o: In function `zlib_reset':
/usr/local/binary/services/libpng-1.6.32/contrib/tools/pngfix.c:2184: undefined reference to `z_inflateReset2'
./.libs/libpng16.so: undefined reference to `z_deflateEnd'
./.libs/libpng16.so: undefined reference to `z_crc32'
./.libs/libpng16.so: undefined reference to `z_inflateValidate'
./.libs/libpng16.so: undefined reference to `z_deflateReset'
./.libs/libpng16.so: undefined reference to `z_deflate'
./.libs/libpng16.so: undefined reference to `z_inflateReset'
./.libs/libpng16.so: undefined reference to `z_adler32'
./.libs/libpng16.so: undefined reference to `z_deflateInit2_'
collect2: error: ld returned 1 exit status
make[1]: *** [pngfix] Error 1
make[1]: Leaving directory `/usr/local/binary/services/libpng-1.6.32'
make: *** [install] Error 2

```

**Comment by ben29** [comment]
what it's wrong ?

**Comment by glennrp** [comment]
Your linker is finding an old zlib instead of the new one you just built.  Maybe you can do something with LD_LIBRARY_PATH.

**Comment by ben29** [comment]
how can i do that?

**Comment by Nonnis-M** [comment]
I'm facing the same issue... As @glennrp  said there are two version of lib installed lib on my system 1.2.8 and 1.2.9
There is a way to remove the older or force libpng to use the newer?

For the 2nd goal I'm expecting that configuring libpng with --with-zlib-prefix option with the 1.2.9 path should be enough, but the error undefined reference to 'inflateValidate' still exists.
