### ISSUE TITLE
Type casts for allocation size in pngrtran.c

### ISSUE THREAD

**Issue by irwir** [glennrp/libpng#175]
There are a few calls of _png_malloc_ and _png_calloc_ in module **pngtran.c**, where the second parameter (allocation size) is cast to  _png_uint_32_ - possibly for historic reasons.
But declaration defines second parameter as memsize type (_png_alloc_size_t_).
Therefore these casts are mostly unnecessary and could be incorrect in 64-bit mode.

**Comment by glennrp** [comment]
Thanks.  Fixed in pngrtran.c of the libpng16 branch of the GIT repos.

**Comment by glennrp** [comment]
Also fixed in libpng14 and libpng15.  libpng12 uses png_uint_32 consistently and libpng17 has been rewritten to mostly not use typecasting.

**Comment by irwir** [comment]
There are other cases of unnecessary (and thus potentially incorrect type casts) in other modules.
Shall this particular issue be closed, or it might be continued here?

**Comment by glennrp** [comment]
You may leave this open and report other similar problems here.

Thanks

**Comment by irwir** [comment]
File **png.c**, function _png_icc_profile_error_. At lines 1915 and 1920 the 4th parameter is cast to _unsigned_ while declaration was _png_alloc_size_t_.

**Comment by irwir** [comment]
File **pngtrans.c**, line 612. Cast to _unsigned int_ instead of _png_size_t_. Maybe cast is not needed at all because _dp-row_ value already has memsize type.

**Comment by glennrp** [comment]
I changed it to png_size_t because dp and row are png_bytep.
