### ISSUE TITLE
CMake build failing when cross compiling to Android NDK

### ISSUE THREAD

**Issue by rcdailey** [glennrp/libpng#178]
On `master`, I am not able to build on Android. Here is the error I get:

```
-- [1/64] Generating pngprefix.h
[2/64] Generating scripts/symbols.out
FAILED: scripts/symbols.out
cmd.exe /C "cd /D E:\code\frontend\android_release\third_party\build\libpng && "E:\Program Files\CMake\bin\cmake.exe" -DINPUT=E:/code/frontend/source/Core/ThirdParty/libpng/source/scripts/symbols.c -DOUTPUT=E:/code/frontend/android_release/third_party/build/libpng/scripts/symbols.out -P E:/code/frontend/android_release/third_party/build/libpng/scripts/genout.cmake"
clang.exe: warning: argument unused during compilation: '-mfloat-abi=softfp' [-Wunused-command-line-argument]
clang.exe: warning: argument unused during compilation: '-mfpu=vfpv3-d16' [-Wunused-command-line-argument]
clang.exe: warning: argument unused during compilation: '-mthumb' [-Wunused-command-line-argument]
clang.exe: warning: argument unused during compilation: '-Wa,--noexecstack' [-Wunused-command-line-argument]
error: unknown target CPU 'armv7-a'
CMake Error at scripts/genout.cmake:78 (message):
  Failed to generate
  E:/code/frontend/android_release/third_party/build/libpng/scripts/symbols.out.tf1
```

I'm targetting `armeabi-v7a` using `clang` compiler. My NDK is r15b. I'm using the toolchain file provided by the NDK itself.

@glennrp Please let me know if this is an issue in your CMake scripts. If so, I am happy to help contribute any changes needed. I'm not sure what the problem is at this point.

**Comment by glennrp** [comment]
Please try again with git head.

**Comment by rcdailey** [comment]
I just realized that this doesn't work using `master`, but using `libpng16` does work (I presume this is where you have been making your fixes).

**Comment by glennrp** [comment]
Right, "master" won't be updated until 1.6.33 is released.

**Comment by rcdailey** [comment]
Good to know. Since I verified this seems to be building, I will close this issue. Again thank you for your fixes. If anything else comes up, I'll reopen and let you know.

**Comment by rcdailey** [comment]
I found a few issues that only appear when building on Windows.

1. `project(libpng ASM C)` causes errors due to ASM. This works: `project(libpng C)`. But I have to question why you're specifying the language explicitly: CMake already knows to set the language per-file you add to targets based on their extension. For example, `*.c` files already compile using C, and `*.asm` files are assembler, etc.
2. Parallel builds are not enabled in MSVC. This can be fixed by adding this somewhere:

   ```
   if(MSVC)
       add_definitions(/MP)
   endif()
   ```

I'm happy to submit a patch with these changes, or you can make them yourself. First I wanted to see how you felt about it. Thanks in advance.

**Comment by rcdailey** [comment]
I'm working on a PR for you with these changes. There's also a few other changes I'm making, which are mostly cleanup.

**Comment by starseeker** [comment]
Unless someone knows of a specific reason libpng needs to specify C, I'd agree that the language shouldn't be explicitly set.

**Comment by rcdailey** [comment]
By default CMake defines project languages C and CXX. So he's trying to exclude tool chain requirements for C++. So what he's doing is actually correct. ASM doesn't make sense though, since this is different per OS.
