### ISSUE TITLE
Possibly unnecessary condition check

### ISSUE THREAD

**Issue by irwir** [glennrp/libpng#180]
File _pngrutil.c_, line 740:
`if (ret == Z_STREAM_END)`
Either if-then-else structure around this line should be reconsidered or the check could be omitted.

**Comment by glennrp** [comment]
I'm not sure about the original intent, but certainly as it stands the test
is rendundant.  Fixed in libpng16 branch.

**Comment by glennrp** [comment]
Problem seems to exist only in the libpng16 branch.

**Comment by irwir** [comment]
Reopening this issue because there are two more checks that could be omitted.

File pngrutil.c, line 1588:
`else if (size > 0)`
Unsigned variable is not equal to 0, therefore the condition is always true. Though it could be left as a comment.

File _pngwrite.c_, line 1943:
`int write_16bit = linear && !colormap && (display->convert_to_8bit == 0);`
_!colormap_ was already evaluated in _linear_ variable.

**Comment by glennrp** [comment]
Agreed.

**Comment by irwir** [comment]
Looking at the old code in _pngrutil.c_ it might be expected to see:
 ```
#ifndef __COVERITY__
                                     errmsg = png_ptr->zstream.msg;
#endif
                                 }
                                else
                                    errmsg = "truncated";
```
