### ISSUE TITLE
what is the problem with this png image

### ISSUE THREAD

**Issue by sturkmen72** [glennrp/libpng#183]
![crop_000010a](https://user-images.githubusercontent.com/12151541/32344092-b1eefb8a-c016-11e7-9ab4-3e08fa0564c5.png)

i am using OpenCV and tried to use latest version of libpng in OpenCV. i can't open the image above when i use newer versions of libpng than 1.6.25 

error message `libpng error: IDAT: invalid distance too far back`
my OS is windows 10 64bit

**Comment by glennrp** [comment]
As you reported, and according to "pngcheck -v" it contains the "too far back" error in the IDAT (zlib) data.  You can use
pngfix to repair it.  pngifx comes with the libpng16 distribution, and you run

`pngfix --out=problem-fixed.png problem.png
`
Do you happen to know how the image was created?

Glenn

**Comment by sturkmen72** [comment]
thank you for the explanation

it is one of [INRIA Person Dataset](http://pascal.inrialpes.fr/data/human/) images ( most of them has same problem)

**Comment by liquidmetal** [comment]
Could you attach a link to the original png file? The embedded image might have gone through Github's image compression.

**Comment by sturkmen72** [comment]
@liquidmetal thank you for your care. you can use the image above. https://user-images.githubusercontent.com/12151541/32344092-b1eefb8a-c016-11e7-9ab4-3e08fa0564c5.png
