### ISSUE TITLE
Conan package for libpng

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [glennrp/libpng#185]
Hello
Do you know about Conan package manager? Can you add Conan package for libpng and maintain it? Here you can find example of my conan recipe for libpng: https://github.com/ZaMaZaN4iK/conan-libpng

**Comment by glennrp** [comment]
Would you be more specific about what files would need to be added to the libpng source distribution?  Assume they would go in contrib/conan or projects/conan.

**Comment by ctruta** [comment]
I may explore C/C++ package managers (e.g. Build2, Conan, Vcpkg) in some future. For the time being, however, I'd like to focus on getting the existing infrastructure fully working, and to sort out the existing defects.
I understand that external projects (Conan and Vcpkg) can handle libpng quite well, already.
