### ISSUE TITLE
CMake in project put ASM at the end

### ISSUE THREAD

**Issue by jkfindeisen** [glennrp/libpng#196]
I propose to change line 34 in CMakeLists.txt from `project(libpng ASM C)` to `project(libpng C ASM)`. Reason is that CMake uses the C compiler on some systems to detect ASM capabilities and therefore order matters here.

Example: CMake with MSVC 2015 as generator will generate an error (No ASM compiler found) without the change but not with the change.

Please see this [CMake issue](https://gitlab.kitware.com/cmake/cmake/issues/17532) for a confirmation from CMake and their proposed update to the CMake documentation recommending this.

Since I don't know to which branch of libpng to make a PR and it's a really small change I just post it here as an issue.

**Comment by scribam** [comment]
@jkfindeisen Done with commit f07b985ddb73329bead8a46df3e0e80081e3acc4?
