### ISSUE TITLE
png_get_io_ptr error png_ptr

### ISSUE THREAD

**Issue by shreyasck** [glennrp/libpng#201]
Hi,

I'm currently using the following to write a PNG to a memory buffer,

 and I checked this link https://stackoverflow.com/a/1823604/3304719

implemented the same 
I will give the snippet of my code 

struct mem_encode
{
	char *buffer;
	size_t size;
};
void user_write_data(png_structp png_ptr, png_bytep data, png_size_t length) {
       struct mem_encode* p = (struct mem_encode*)png_get_io_ptr(png_ptr);         // here png_ptr something is wrong
	size_t nsize = p->size + length;
	if (p->buffer)
		p->buffer == realloc(p->buffer, nsize);
	else
		p->buffer == malloc(nsize);
	if (!p->buffer)
		png_error(png_ptr, "Write Error");   
	memcpy(p->buffer + p->size, data, length);
	p->size += length;
}
void user_flush_data(png_structp png_ptr) {
}

BOOL GeneratePNG(mem_encode& state, const long lWidth, const long lHeight, const long lDepth, BYTE* pucImageData)
{
BOOL bSave = FALSE; //i will flag this in saving and freeing of png_ptr
//bla bla here info_ptrpng_set_IHDR, row_pointers these code

png_set_rows(png_ptr, info_ptr, row_pointers);
png_set_write_fn(png_ptr, &state, user_write_data, user_flush_data);// If we'r not using IO operation 
png_write_png(png_ptr, info_ptr, PNG_TRANSFORM_IDENTITY, NULL);

return bSave;
}
 int main ()
{
//something to output
}

and my png lib version is 1.6.34

**Comment by ctruta** [comment]
This is not a clearly-reproducible defect report. Rejecting.
