### ISSUE TITLE
PCS illuminant is not D50

### ISSUE THREAD

**Issue by boxerab** [glennrp/libpng#207]
When storing to libpng with an ICC profile  I am getting an error about PCS illuminant.
Is it possible to trap this error, and simply not store the ICC profile. Otherwise, the whole
storage routine fails.

**Comment by glennrp** [comment]
look for "sRGB_CHECK" in the manpage to see how to disable the check.

**Comment by boxerab** [comment]
Thanks! I already disable this check, but I still get this error

**Comment by boxerab** [comment]
libpng error: profile 'ColorSpin': 0h: PCS illuminant is not D50

**Comment by boxerab** [comment]
Related post:  https://sourceforge.net/p/libpng/bugs/256/

**Comment by boxerab** [comment]
Here is the original TIFF file with the ICC profile. I encode this as jpeg 2000, then try to decode to PNG and get this error.

[ICC_profile_test_image_Farbkreis_120grad.zip](https://github.com/glennrp/libpng/files/1714540/ICC_profile_test_image_Farbkreis_120grad.zip)

**Comment by boxerab** [comment]
So, I ended up solving my problem by turning this error into a warning:

`png_set_benign_errors(png_struct, 1);`
