### ISSUE TITLE
Parentheses in macros

### ISSUE THREAD

**Issue by irwir** [glennrp/libpng#216]
Line 1639 in `pngwrite.c` would be safer with the parenthesized paramer:
`#   define UNP_RECIPROCAL(alpha) ((((0xffff*0xff)<<7)+((alpha)>>1))/(alpha))`
That would ensure proper evaluation of expressions such as `UNP_RECIPROCAL(a + 1)`.

Similar changes might be applicable to `buffer` parameter at the line 1746 in `pngpriv.h`.

**Comment by ctruta** [comment]
Thank you. I will include your change in the next libpng release.

**Comment by ctruta** [comment]
Resolved.
