### ISSUE TITLE
Make Failed: Awk generates pnglibconf.h error

### ISSUE THREAD

**Issue by KangLin** [glennrp/libpng#222]
Error information:

In file included from ../contrib/tools/pngcp.c:18:0:
./pnglibconf.h:205:54: error: expected identifier or '(' before '-' token
                                                 0
                                                      ^
In file included from C:/Qt/Qt5.9.4/Tools/mingw530_32/i686-w64-mingw32/include/_mingw.h:275:0,
                 from C:/Qt/Qt5.9.4/Tools/mingw530_32/i686-w64-mingw32/include/crtdefs.h:10,
                 from C:/Qt/Qt5.9.4/Tools/mingw530_32/i686-w64-mingw32/include/stdio.h:9,
                 from ../contrib/tools/pngcp.c:42:

Looking at pnglibconf.h found awk generated error:

![default](https://user-images.githubusercontent.com/8564669/39035478-c6648920-44ac-11e8-8ae2-4f7cd0a1acb5.png)

Awk generated ^M

Environment:
l@DESKTOP-TU5KKKO MSYS /d/source/RabbitIm/ThirdLibrary/build_script
$ uname -a
MSYS_NT-10.0 DESKTOP-TU5KKKO 2.10.0(0.325/5/3) 2018-02-09 15:25 x86_64 Msys

l@DESKTOP-TU5KKKO MSYS /d/source/RabbitIm/ThirdLibrary/build_script
$ awk -V
GNU Awk 4.2.0, API: 2.0 (GNU MPFR 4.0.1, GNU MP 6.1.2)

gcc version 7.3.0 (Rev1, Built by MSYS2 project)

Operating system:
windows 10

**Comment by ctruta** [comment]
It appears that you had the file altered accidentally. The original source should look like this:
```
#define PNG_TEXT_Z_DEFAULT_COMPRESSION (-1)
#define PNG_TEXT_Z_DEFAULT_STRATEGY 0
```
Please retry with a fresh libpng source tree. That should work.

**Comment by KangLin** [comment]
@ctruta Yes. Modify the file. is OK. but the file is awk generates

**Comment by ctruta** [comment]
Ok, thank you for clarifying. I'll look into it.

**Comment by ctruta** [comment]
Try libpng-1.6.35, which I've just published.

I see that you are on Windows, and you may be affected by some sort of automated CRLF conversion of the source code (specifically the AWK script). If you're still experiencing this issue, try using the .zip or .7z archives. These ones have already been converted to CRLF, hopefully in a correct way.

**Comment by KangLin** [comment]
Still wrong, please see:
https://ci.appveyor.com/project/KangLin/rabbitthirdlibrary/build/v0.0.5.438/job/xxc3wv6f5wk17m1b
