### ISSUE TITLE
libpng can't be compiled without libm on Linux

### ISSUE THREAD

**Issue by kutschkem** [glennrp/libpng#234]
The CMakeLists.txt looks like building is supposed to be possible without libm. However M_LIBRARY is not set to "" and stays NOT_FOUND. Then later it is used in target_link_library, which breaks the build. If this is supposed to be a supported use case, then if libm is not found, M_LIBRARY should be set to "" like in the Windows Case, or checked later to ensure it is not linked against.

**Comment by ctruta** [comment]
Could you please confirm whether this issue is fixed in libpng-1.6.36 or later?

**Comment by ctruta** [comment]
Fixed.
