### ISSUE TITLE
SOLVED

### ISSUE THREAD

**Issue by sug0** [glennrp/libpng#252]
I've been working on an image processing library that is wrapping libpng to handle png encoding and decoding. My encoding routine seems to work just fine, however not the same can be said about the decoding routine...

Here's a screenshot with a few example images being decoded:

![](https://u.sicp.me/gRAFU.png)

`test.png` was created by my library, and consequently by libpng, and is decoded just fine, no errors nor warnings are reported. As for the other `test_pika*.png` images, libpng displays a warning about the pixel row filter value being wrong... I have no idea why.

Here's the code for my decoding routine:
https://github.com/sugoiuguu/libgoimg/blob/29f33c6a56ffe694b6ba584c60cc6e71a8fce0ef/fmt_png.c#L37

Any help is appreciated!

Thanks,
Tiago Carvalho

**Comment by ProgramMax** [comment]
@ctruta I think we can close this

**Comment by sug0** [comment]
oops it's been a couple of years. yep, for sure! thanks for the heads up @ProgramMax
