### ISSUE TITLE
Access to the new vendor_ccs in OSSFuzz

### ISSUE THREAD

**Issue by posidron** [glennrp/libpng#317]
Hi,

I am writing you because you have a project in OSSFuzz.

We (Fuzzing Team at Mozilla) moved recently most of our LibFuzzer fuzzers to OSSFuzz except the ones for which already a fuzzer existed in OSSFuzz. We would like to receive bug notifications from those fuzzers which were not contributed by us in order to inform our developers to prepare for upstream updates as early as possible. In order to get added to the new ‘vendor_ccs’ field in project.yml we need your permission as project owner of the underlying library. [1]

If you could give me short reply with a “yay” or “nay” that would be much appreciated.

Thanks for your time.

[1] https://github.com/google/oss-fuzz/pull/2703

**Comment by ctruta** [comment]
Hello, Fuzzing Team,

Sorry for my very late reply. I'm going over the issues in this account, which I haven't afforded to do in months.

The answer is _"yay, of course, and thank you very much!"_
I hope I haven't incommodated you too badly, by not responding earlier; and apologies if I did.

Sincerely,
Cosmin
