### ISSUE TITLE
Duplicate line in pngrutil.c

### ISSUE THREAD

**Issue by irwir** [glennrp/libpng#334]
An extra line (probably a copy-paste error), that existed for years but was not spotted because it breaks nothing.
https://github.com/glennrp/libpng/blob/301f7a14295a3bdfaf406dbb5004d0784dc137ea/pngrutil.c#L304-L305

**Comment by benkasminbullock** [comment]
I've added that to this pull request:

https://github.com/benkasminbullock/libpng/commit/158f10f2519d51b5816b55588873b649708cf29c
