### ISSUE TITLE
A variable is assigned values twice successively

### ISSUE THREAD

**Issue by rainoftime** [glennrp/libpng#341]
Hi, at pngrutil.c, Line 304 and Line 305 seem duplicates
~~~~
 if (buffer != NULL && new_size > png_ptr->read_buffer_size)
   {
      png_ptr->read_buffer = NULL;
      png_ptr->read_buffer = NULL;   
      png_ptr->read_buffer_size = 0;
      png_free(png_ptr, buffer);
      buffer = NULL;
   }
~~~~

**Comment by benkasminbullock** [comment]
This seems to be fixed in the most recent commit:

https://github.com/glennrp/libpng/blob/a37d4836519517bdce6cb9d956092321eca3e73b/pngrutil.c#L304

**Comment by benkasminbullock** [comment]
It was fixed here:

https://github.com/glennrp/libpng/commit/3796518809b03e347393e630fe91ab7a3dd0dcc9
