### ISSUE TITLE
Can't build with CMake nightly for Xcode

### ISSUE THREAD

**Issue by meshula** [glennrp/libpng#344]
CMake nightly removes support for the old Xcode build system, and the CMake script for libpng now fails as shown below. 

A hacky workaround is to comment out the line that searches for awk.

```py
#find_program(AWK NAMES gawk awk)
```

```
CMake Error in CMakeLists.txt:
  The custom command generating

    /Users/nporcino/dev/usd-dev-install/build/libpng-1.6.37/pnglibconf.out

  is attached to multiple targets:

    genfiles
    gensym
    genvers

  but none of these is a common dependency of the other(s).  This is not
  allowed by the Xcode "new build system".


CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by vespakoen** [comment]
Adding some search keywords: macOS, Apple

This is indeed a problem right now, I worked around this by using
```
cmake_policy(SET CMP0048 OLD)
```

Or by not using XCode generator.

One of the too, or both, I don't remember.

**Comment by AndyMender** [comment]
I ran into the same issue recently when updating to libpng 1.6.36. Unfortunately, setting `cmake_policy(SET CMP0048 OLD)` alone doesn't help and it looks like the only viable solution is to use `Ninja` or `Makefile` as the cmake generator.

**Comment by meshula** [comment]
My opinion is that if eliding a search for awk allows successful Xcode project generation, then the cmake script can be changed to not search for awk when generating Xcode files. I would have submitted a PR, but I did not have time to search for the reason awk is a requirement in the first place, and whether it is somehow in some circumstances required for Xcode project file generation. I would consider fixing the Cmake script a viable solution, if indeed not searching for awk is a fix.

**Comment by AJenbo** [comment]
I wonder if this is the same issue as we also encountered with Android builds recently: https://github.com/glennrp/libpng/commit/5cfc16530ae7f2c1f1c88ecd08b0fde2e2a4cd93

**Comment by glebm** [comment]
The "multiple targets" warning is correct, the targets that depend on the custom command must **also** depend on the custom target.

From CMake documentation:

> Do not list the output in more than one independent target that may build in parallel or the two instances of the rule may conflict (instead use add_custom_target to drive the command and make the other targets depend on that one).

This is a bug relevant to all generators.

**Comment by ctruta** [comment]
Fixed. Many thanks to @glebm for contributing #403.

**Comment by meshula** [comment]
Thanks so much! 

Any possibility of tagging a point release? Our build automation prefers to fetch against point release tags.

**Comment by ctruta** [comment]
I have a few more contributions to integrate, and I'd like to give it an extra week for extra testing. If all goes well, I should be able to publish a point release by next weekend.

**Comment by ctruta** [comment]
@meshula it's done. Enjoy our latest and greatest libpng-1.6.38.

**Comment by meshula** [comment]
Sweet!!
