### ISSUE TITLE
arm/filter_neon.S:24:17: error: expected string in directive

### ISSUE THREAD

**Issue by zy3274311** [glennrp/libpng#347]
An error occurred while building the android library.
[Android other_build_systems](https://developer.android.com/ndk/guides/other_build_systems)
![image](https://user-images.githubusercontent.com/4082936/96109524-4c116080-0f11-11eb-8e40-ea9545811ed0.png)

**Comment by DanAlbert** [comment]
Note that the line with the error is specifically in an `#ifdef __clang__`, and this is an Arm specific (right?) source file. Not sure this line is correct in any configuration, but a6fc80300fc9eb49beca243612d018787ec293d4 added this and did nothing else so I'm missing something.

**Comment by benkasminbullock** [comment]
This issue was also discussed on stackoverflow.com:

https://stackoverflow.com/questions/63603833/problem-with-using-the-ndk-with-other-build-systems

The screenshot above says `compile ... -clang` so it looks like something to do with clang.

**Comment by dnfield** [comment]
This is my fault. This probably needs to be guarded by __APPLE__ or something like that. Looking into it.

**Comment by mgood7123** [comment]
when is this going to be merged?

**Comment by zchrissirhcz** [comment]
Me same here. Suggest merge PR #383 , thanks.
