### ISSUE TITLE
1.6.36 and 1.6.37 not good here

### ISSUE THREAD

**Issue by Neustradamus** [glennrp/libpng#365]
Latest release: v1.6.35 /  c17d164:
- https://github.com/glennrp/libpng
- https://github.com/glennrp/libpng/releases

No release here for 1.6.36 and 1.6.37 like 1.6.35.

Can you solve it?

**Comment by benkasminbullock** [comment]
For reference, the sourceforge download links are here:

https://sourceforge.net/projects/libpng/files/libpng16/1.6.37/

and here:

https://sourceforge.net/projects/libpng/files/libpng16/1.6.36/

**Comment by Neustradamus** [comment]
Note:
- Tags: https://github.com/glennrp/libpng/tags
VS
- Releases: https://github.com/glennrp/libpng/releases

**Comment by harkue** [comment]
which is the office repo of libpng?
 - https://github.com/glennrp/libpng
 - https://sourceforge.net/p/libpng/code/ci/master/tree/

**Comment by Neustradamus** [comment]
Any news?

**Comment by Neustradamus** [comment]
@ctruta: After more than 2,5 years...

Can you remove the only old release 1.6.35 here:
- https://github.com/glennrp/libpng/releases

To see the problem, we can see here at right on the GitHub project homepage:
- https://github.com/glennrp/libpng

Releases 1
libpng-1.6.35
Latest on 16 Jul 2018

It is because after the tag, there is a not the release...
- https://github.com/glennrp/libpng/tags

**Comment by ctruta** [comment]
Hello, and apologies for not paying attention. I removed the old release libpng-1.6.35, and I ostensibly did not add any new ones, because the archives are not identical to the official releases published on SourceForge and on libpng.org.
