### ISSUE TITLE
Crash caused by png_jmpbuf pointer being misaligned on Windows x64

### ISSUE THREAD

**Issue by jwtowner** [glennrp/libpng#368]
Hello libpng team,

This crash occurs on 64-bit Windows 10 on x86-64 CPUs when invoking `setjmp` passing in the `jmp_buf` pointer returned by `png_jmpbuf`. What happens is that a memory access violation exception occurs, due to `setjmp` executing the `movdqa` instruction to store 128-bit XMM registers to memory, but the `jmp_buf` pointer returned by `png_jmpbuf` only has 8-byte alignment. Ultimately, the problem can be traced back to `png_create_read_struct`/`png_create_write_struct` using `malloc` to allocate memory for the `png_struct_def`, which unfortunately, due to historical reasons with the `HeapAlloc` Win32 API call, only guarantees 8-byte alignment for allocated memory blocks.

The work around is to of course use `png_create_*_struct_2` set of APIs, passing in callbacks for user-defined memory allocation that does guarantee at least 16-byte alignment for memory blocks. For example, these callbacks can simply delegate to the MSVC++ CRT `_aligned_alloc`/`_aligned_free` functions. Indeed, this is the workaround I've implemented for FreeType [here](https://gitlab.freedesktop.org/freetype/freetype/-/merge_requests/15?commit_id=2efc602f93297cc41e656621600a2278edbbe710).

However, I believe this issue likely affects a lot of other libraries downstream that make use of libpng. Would you be willing to accept a patch for this here? Any thoughts on how to best address this in libpng? Is it just a matter of updating the library to allocate `png_struct_def` instances with `_aligned_malloc` instead of `malloc` on 64-bit Windows? Or do you think it may be more involved than that?

Thanks!

And for more information, this issue is also being tracked in these two following locations:

https://gitlab.freedesktop.org/freetype/freetype/-/issues/1037
https://github.com/microsoft/vcpkg/issues/16418

**Comment by apodtele** [comment]
Microsoft describes [malloc](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/malloc) with 64-bit alignment on 64-bit targets. Are you sure???

**Comment by jwtowner** [comment]
> Microsoft describes [malloc](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/malloc) with 16-byte (128-bit) alignment on 64-bit targets. Are you sure???

You're right, this issue actually doesn't exist in libpng or with malloc. False alarm on my end caused by third-party middleware hooking the HeapAlloc function that I was unaware of, that did not provide the 16-byte alignment guarantee. My apologies for not having noticed it sooner. Closing this issue.
