### ISSUE TITLE
Missing SIMD optimized filters

### ISSUE THREAD

**Issue by bitbank2** [glennrp/libpng#376]
Some of the different pixel size permutations are missing from the SIMD implementations and the existing ones don't look to be optimal. Is there a reason the missing ones were skipped?

**Comment by randy408** [comment]
What do you mean by not optimal? 3- and 4-byte per pixel formats are the most common.

**Comment by bitbank2** [comment]
Not optimal means that they can be written better. Yes, the 3 and 4 byte ones are more common. The 1-byte ones are missing entirely.

**Comment by bitbank2** [comment]
Since this repo is no longer active, I'm closing this issue.

**Comment by benkasminbullock** [comment]
Since there are not many other places you can report to, you may as well leave it open here until something is done about the current situation.

**Comment by bitbank2** [comment]
I am probably the one that's going to do something about it :)
I already wrote and tested the code, but I'm going to push it to Cosmin Truta's repo since he's the current active admin of libpng.

**Comment by benkasminbullock** [comment]
He is using this repo though, I've put through a number of pull requests here.
