### ISSUE TITLE
PNG 2 rgb bad case

### ISSUE THREAD

**Issue by 781545872** [glennrp/libpng#389]
Here is my png image,it's a screenshot from my iphone11.
![bad](https://user-images.githubusercontent.com/13492988/128453532-ea1f0958-d771-44be-9ea5-5eefb2438daa.png)
I decode png using code bellow.
```
int main() {
    png_image image;
    memset(&image, 0, sizeof(image));
    image.version = PNG_IMAGE_VERSION;
    png_image_begin_read_from_file(&image, "/Users/qinghuan/Downloads/bad.png");
    image.format = PNG_FORMAT_RGBA;
    int size = PNG_IMAGE_SIZE(image);
    unsigned char*data = (unsigned char*) malloc(size);

    png_image_finish_read(&image, NULL, data, 0, NULL);

    FILE *fp = fopen("/Users/qinghuan/Downloads/bad.rgb", "wb");
    fwrite(data, size, 1, fp);
    fclose(fp);
    return 0;
}
```
png version is: 1.6.37
when I use ffplay to display bad.rgb, its color has been changed.
![image](https://user-images.githubusercontent.com/13492988/128454301-0173499b-5a7a-4f11-a2cb-3e57a3b8774b.png)
Anybody knows what happend?Is there anything wrong in my code?

**Comment by 781545872** [comment]
png_image_begin_read_from_file and png_image_finish_read are high level api, they will not process gamma correction. Using `png_read_png` instead will solve this bad case.

**Comment by ValZapod** [comment]
> will not process gamma correction

There is no gamma corection on the file. it has sRGB chunk which overwrites gAMA and cHRM chunks, so there is a normal transfer function, not gamma.

**Comment by ValZapod** [comment]
And there is also PNG iCCP (353 bytes) chunk that also overwrites sRGB chunk. That has common to iPhones and all apple photos too BTW display P3 with quite invalid 

  | 3)  RedMatrixColumn = 0.51512 0.2412 -0.00105

since negative values are not allowed, and yet everyone uses it. So the image is P3-D65 primaries and sRGB trasnfer. BTW, wow.
