### ISSUE TITLE
win-arm64 is not recognised as arm platform by pngpriv.h config with MSVC

### ISSUE THREAD

**Issue by gaborkertesz-linaro** [glennrp/libpng#398]
ARM neon intrinsics are enabled for ARM64 platforms, while older ARM platforms gets the assembly implementation of Neon optizimation.
Linux toolchaing sets __aarch64__ attribute, whil MSVC sets _M_ARM64 only, so the configuration is not set properly for win-arm64 platform with MSVC.

**Comment by hmartinez82** [comment]
@gaborkertesz-linaro We should just merge the same change here. I'll create a PR
