### ISSUE TITLE
Those two corrupted jpeg let libjpeg crash

### ISSUE THREAD

**Issue by Qlex42** [glennrp/libpng#409]
Hi

Those two corrupted JPEG let libjpeg 9e of 16-Jan-2022 crash at opening

[ALV4_Sol_TEXTURE.zip](https://github.com/glennrp/libpng/files/7927608/ALV4_Sol_TEXTURE.zip)
[ALV2_2B_11732x1600_TEXTURE_Chris.zip](https://github.com/glennrp/libpng/files/7927609/ALV2_2B_11732x1600_TEXTURE_Chris.zip)

Hoping this will helps 

Best regards

**Comment by Qlex42** [comment]
sorry not libpng related, I do not know ho I get your github link from jpeg, 
sorry for this noisy one
I send my bug report to jpeg-info@jpegclub.org
best regards

**Comment by ValZapod** [comment]
Those two files are not JPEG, those are JPEG-LS, because both have 0xFFF7 in the stream which means SOF48, signaling JPEG-LS. Not that they actually work with reference decoder. https://github.com/team-charls/charls

**Comment by Qlex42** [comment]
Indeed yes thanks for your feedback, My issue was a bad longjump exception management that introduce crash in the caller application.

All the best
