### ISSUE TITLE
There is no `makefile.system` file.

### ISSUE THREAD

**Issue by Basilisvirus** [glennrp/libpng#434]
I am following the [installation instructions](https://github.com/glennrp/libpng/blob/libpng16/INSTALL).

I am on windows 10 and using Visual studio 2022, and running the make/cmake commands via the VStudio's power shell.

I try to run the part` III. Using scripts/makefile*`
But when I run the  `cp scripts/makefile.system makefile`, it says there is no makefile.system file. Indeed, this file is not there. Why there is no such file in the directory? are the installation instructions too old?

**Comment by spaette** [comment]
The `projects/vstudio/*/*.vcxproj` value for `ToolsVersion` is circa VS2010.

```
$ date
Sun Sep 25 15:17:16 CDT 2022
$ git clone -q https://github.com/glennrp/libpng.git
$ ls libpng/scripts/makefile*
libpng/scripts/makefile.32sunu   libpng/scripts/makefile.hpux
libpng/scripts/makefile.64sunu   libpng/scripts/makefile.ibmc
libpng/scripts/makefile.acorn    libpng/scripts/makefile.intel
libpng/scripts/makefile.aix      libpng/scripts/makefile.linux
libpng/scripts/makefile.amiga    libpng/scripts/makefile.mips
libpng/scripts/makefile.atari    libpng/scripts/makefile.msys
libpng/scripts/makefile.bc32     libpng/scripts/makefile.netbsd
libpng/scripts/makefile.beos     libpng/scripts/makefile.openbsd
libpng/scripts/makefile.clang    libpng/scripts/makefile.sco
libpng/scripts/makefile.darwin   libpng/scripts/makefile.sggcc
libpng/scripts/makefile.dec      libpng/scripts/makefile.sgi
libpng/scripts/makefile.dj2      libpng/scripts/makefile.so9
libpng/scripts/makefile.emcc     libpng/scripts/makefile.solaris
libpng/scripts/makefile.freebsd  libpng/scripts/makefile.std
libpng/scripts/makefile.gcc      libpng/scripts/makefile.sunos
libpng/scripts/makefile.hp64     libpng/scripts/makefile.vcwin-arm64
libpng/scripts/makefile.hpgcc    libpng/scripts/makefile.vcwin32
$ sed -n 75,78p libpng/INSTALL
The files that are presently available in the scripts directory
are listed and described in scripts/README.txt.

Or you can use one of the "projects" in the "projects" directory.
$ grep ToolsVersion libpng/projects/vstudio/libpng/libpng.vcxproj
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
$ 
```

The `contrib/visupng` directory `.dsp` and `.dsw` file extensions would indicate they are rather old.

```
$ cat libpng/contrib/README.txt

This "contrib" directory contains contributions which are not necessarily under
the libpng license, although all are open source.  They are not part of
libpng proper and are not used for building the library, although some are used
for testing the library via "make check".
$ ls libpng/contrib/visupng/*{.dsp,.dsw}
libpng/contrib/visupng/VisualPng.dsp  libpng/contrib/visupng/VisualPng.dsw
$ 
```

NB: With zlib-1.2.12  its contrib/masmx64 and contrib/masmx86 directories were removed.

**Comment by spaette** [comment]
I presently don't have access to a Windows box.

**Comment by spaette** [comment]
You might try the following.

`cp scripts/makefile.vcwin32 makefile`

**Comment by spaette** [comment]
@Basilisvirus 

Have your questions been addressed?

If so, you may want to close this issue.

**Comment by Basilisvirus** [comment]
@spaette Not yet, I am still trying to compile it for windows. As someone mentioned in another issue of mine here, the documentation is old + I am new to making windows/linux apps.
I have years of experience with MCU programming/PCb design, this is not too much out of my scope.

**Comment by spaette** [comment]
age of documentation

scripts/README.txt

`makefile.vcwin32  =>  makefile for Microsoft Visual C++ 4.0 and later`

projects/vstudio/libpng/libpng.vcxproj

> With zlib-1.2.12 its contrib/masmx64 and contrib/masmx86 directories were removed.

another possibility could be when opening `libpng.vcxpro`j in Microsoft's Visual Studio you might be offered to update the file

manually updating such files is not difficult

**Comment by Basilisvirus** [comment]
I see, thanks.
Trying to debug things, I discovered I did not compile the Zlib correctly (used C++ to compile it rather than C), so still working on that. Let the issue open and I will check it again asap.

**Comment by Basilisvirus** [comment]
Following the installation instructions got me nowhere. 
This issue can be closed. I am now following @Tieske909090 's installation instructions found in this issue here: https://github.com/libharu/libharu/issues/135. This got me further and I will open another issue for my problem.
