### ISSUE TITLE
libpng warning: /proc/cpuinfo open failed

### ISSUE THREAD

**Issue by davesworking** [glennrp/libpng#436]
Hi,

could you please let me know the correct way to disable all warnings?

We would like to eliminate "libpng warning: /proc/cpuinfo open failed" on Mac ARM64 platform.

Thanks!

**Comment by ctruta** [comment]
Are you still using version 1.6.37 or earlier? It should be fixed in 1.6.38.

**Comment by davesworking** [comment]
Thanks!

I was, in fact, using 1.6.37. Is there anything else I need besides getting 1.6.38? Any code changes required to disable warnings?

**Comment by ctruta** [comment]
With 1.6.38, it should just work. (If it doesn't, that would be a bug.)
