### ISSUE TITLE
Can a user contact privately the maintainers?

### ISSUE THREAD

**Issue by thealberto** [glennrp/libpng#448]
Hello,
I was wondering if there is an email that can be used in case a user wanted to report an issue privately.

Thanks

**Comment by ctruta** [comment]
This is a very good question!

For security-related issues we used to have a separate mailing list, but we don't have that anymore.

Feel free to email me: ctruta at gmail.com.

If you wish to contact other members of the (admittedly dormant) PNG group privately, it may be a good idea to ask on one of our mailing lists, and see who else is willing to accept the idea of having a private conversation. I personally recommend that you ask on **png-mng-implement**; see http://www.libpng.org/pub/png/pngmisc.html#lists
