### ISSUE TITLE
Some crashes caused by png_get_uint_* and png_save_uint_*

### ISSUE THREAD

**Issue by hopper-vul** [glennrp/libpng#460]
Hi,
   when fuzzing the libpng, we found that the functions `png_get_uint_*` and `png_save_uint_*` are easily to trigger overflows and cause crashes.

The problem functions are: `png_save_uint_32`, `png_get_uint_32`, `png_save_uint_16`, `png_get_uint_16`, `png_get_int_32`, `png_save_int_32` and `png_get_uint_31`. 

The reason of those crashes is these functions **read or write the fixed number bytes (e.g. 4 bytes)** from the input `buf`, and if the length of the passed `buf` is **smaller than the fixed number** and the overflows will happen.

A trigger case is listed bellow:
```
//gcc test.c -o test -lpng -fsanitize=address
#include "png.h"
#include <stdlib.h>
#include <string.h>
typedef uint8_t   u8;   
typedef int32_t i32;
int main() {
    u8 v0_tmp[] = {181, 0, }; // buf
    u8 *v0 = malloc(sizeof v0_tmp);
    memcpy(v0, v0_tmp, sizeof v0_tmp);
    u8 *v1 = v0; // buf
    i32 v2 = png_get_int_32(v1); // $target
}
```

**Comment by ctruta** [comment]
This is not an error in libpng, but in the test case.

The functions `png_get_int_32`, `png_save_int_32`, `png_get_uint_32`, `png_save_uint_32` must operate on a buffer of size 4 or longer. The functions `png_get_uint_16` and `png_save_uint_16` must operate on a buffer of size 2 or longer. These are to be used on the chunk data, and the libpng applications are required to ensure that the chunk data is all there, or else, it must be signaled as a chunk data error.

**Comment by hopper-vul** [comment]
@ctruta 
Oh, many thanks.

I see you have discussed the similar issues in #449 before, and I am curious about do you have a plan to take some remedy actions on such cases?  or just leave the correct usage of those APIs as the responsibilities of libpng user?

Thanks.
