### ISSUE TITLE
The function prototype of `png_write_row` seems to be changed on macos

### ISSUE THREAD

**Issue by ToKiNoBug** [glennrp/libpng#478]
I found that libpng installed from homebrew has a little bit different in the prototype of function `png_write_row`.

The function prototype should be :
```c
void png_write_row(png_structrp png_ptr, png_const_bytep row)
```

But actually it is:
```c
void png_write_row(png_structp, png_bytep)
```

The `const` qualifier is missing, as a result, many code can not be compiled. 

But I believe that things are even worse: libpng built with the second prototype of `png_write_row` can still link to executables that requires `png_write_row` with first prototype, the dynamic linker will not be able to find this error.

I don't think abi can be changed in this way, neither do I know who changed the code. But I believe at least it's necessary for you to know about this error.

By the way, I discovered this in the MacOS virtual machine provided by github action, and the second prototype is picked from error info from gcc. 

The full error message is:
```text
Users/runner/work/SlopeCraft/SlopeCraft/utilities/FlatDiagram/FlatDiagram.cpp:146:26: error: invalid conversion from 'const uint8_t*' {aka 'const unsigned char*'} to 'png_bytep' {aka 'unsigned char*'} [-fpermissive]
  146 |       png_write_row(png, reinterpret_cast<const uint8_t *>(&buffer(pix_r, 0)));
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                          |
      |                          const uint8_t* {aka const unsigned char*}
In file included from /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/zlib.h:34,
                 from /Library/Frameworks/Mono.framework/Headers/png.h:422,
                 from /Users/runner/work/SlopeCraft/SlopeCraft/utilities/FlatDiagram/FlatDiagram.cpp:4:
/Library/Frameworks/Mono.framework/Headers/png.h:1807:32: note:   initializing argument 2 of 'void png_write_row(png_structp, png_bytep)'
 1807 | PNG_EXPORT(void,png_write_row) PNGARG((png_structp png_ptr,
```

**Comment by ToKiNoBug** [comment]
By the way, this api change may happen in 5 days ago, that is, May 15th, 2023. This date is deduced from the CI log of my project, the last successful build is at 5 days ago, and after that day, all build fails with this api change.

**Comment by jbowler** [comment]
It happens if the support for the ANSI-C90 (i.e. the 1990 standard) "const" qualifier isn't present in the compiler.  Clearly const support is present in your compiler so it looks like one of the png*conf.h header files has been installed incorrectly,

I suggest reporting the bug to your cloud provider, or whatever it is you are using; it is, for certain, a downstream bug therefore has to be reported there first.

**Comment by ToKiNoBug** [comment]
> It happens if the support for the ANSI-C90 (i.e. the 1990 standard) "const" qualifier isn't present in the compiler. Clearly const support is present in your compiler so it looks like one of the png*conf.h header files has been installed incorrectly,
> 
> I suggest reporting the bug to your cloud provider, or whatever it is you are using; it is, for certain, a downstream bug therefore has to be reported there first.

okay, I will report it to homebrew.

**Comment by jbowler** [comment]
I suggest cross linking the reports; give homebrew the link to this bug (i.e. https://github.com/glennrp/libpng/issues/478) and copy the homebrew bug link here (or they can do that.)  That keeps things tidy.

**Comment by ToKiNoBug** [comment]
> I suggest cross linking the reports; give homebrew the link to this bug (i.e. #478) and copy the homebrew bug link here (or they can do that.) That keeps things tidy.



I have find out the reason when I'm writting a simplist reproducible example asked by homebrew's issue template. In fact there's nothing wrong with homebrew's libpng.

In fact there's nothing wrong with homebrew's libpng, .
Actually libpng installed by homebrew is not even used, but cmake continually found another eariler version of libpng at `/Library/Frameworks/Mono.framework/Headers/png.h`, but the homebrew one is installed at `/System/Volumes/Data/usr/local/Cellar/libpng/1.6.39`. The version differs a lot (1.4.12 vs 1.6.39). 

The weird function prototype of `png_write_row` is defined in eariler one, probably compiled with an ancient compiler that doesn't support const, according to your analysis.

Now I have asked cmake to find a libpng no eariler than 1.6, and I believe this will work.

**Comment by jbowler** [comment]
The addition of the const prototypes were an ABI change that happened in, IRC, 1.5  I don't know anything about cmake builds, but I assume there is a search path and that is what changed.  It's also possible something else is installing an earlier (very, very, old) libpng earlier on the search path.

If you find you have to support multiple libpng major versions you have to write for the highest common factor and, a lot of the time, check for the different versions and provide different code.  You can also use compiler/OS support for multi-versioned libraries, but those have to be built by the OS provider; there is some support in libpng for doing it but the OS provider has to build from multiple sets of libpng source then perform magic to merge the code.

I strongly advise anyone reading this not to use anything other than libpng 1.6; if necessary a minimal libpng 1.6 can be built and shipped with an application bypassing the old version that is shipped with an OS.
