### ISSUE TITLE
EXIF chunk is written in both png_write_info() and png_write_end() functions

### ISSUE THREAD

**Issue by nickdademo** [glennrp/libpng#480]
After setting the EXIF data via `png_set_eXIf_1`, calling `png_write_info` does not "reset" the EXIF data in the info struct after writing. This means that a later call to `png_write_end` will write the EXIF chunk **again** (after the image data).

According to `exiftool`, the EXIF chunk should be before the image data...

The only way to prevent this 2nd EXIF chunk is to pass the infoptr as `nullptr` in `png_write_end()`, but a consequence of this is not being able to write comments or time info.

I wonder if this is by design?

**Comment by ctruta** [comment]
Hi @nickdademo, thank you for your report.

The issue you're reporting here was well-known. A fix was attempted a few years ago (thanks again @benkasminbullock), but I revert it eventually, because it was incorrect. I just landed a proper fix. See commit e6c5bf46c4fa3e3738a2ed0896ce33fc270e0cac.
