### ISSUE TITLE
tRNS must follow PLTE to be valid

### ISSUE THREAD

**Issue by ProgramMax** [glennrp/libpng#482]
The PNG spec  version 1.2 says:
"When present, the tRNS chunk must precede the first IDAT chunk, and must follow the PLTE chunk, if any."

The default libpng config defined PNG_READ_OPT_PLTE_SUPPORTED and causes a tRNS chunk to be considered invalid and ignored if it comes before the PLTE chunk. However, png_get_valid(png, info, PNG_INFO_tRNS) returns a nonzero value. This could cause a user to allocate extra space, resulting in uninitialized memory.

**Comment by wantehchang** [comment]
Chris: Thank you very much for filing this bug report. Coincidentally, I have been investigating this issue since last Friday.

This issue breaks some (but not all) applications that use the following example code in libpng-manual.txt and example.c:

```
    if (png_get_valid(png_ptr, info_ptr,
        PNG_INFO_tRNS)) png_set_tRNS_to_alpha(png_ptr);
```

Applications that assume the decoded output has alpha if this `png_set_tRNS_to_alpha()` call is made will have memory errors.

Here is a possible fix:

```
diff --git a/pngget.c b/pngget.c
index e44933c0d..e64ec2774 100644
--- a/pngget.c
+++ b/pngget.c
@@ -21,7 +21,18 @@ png_get_valid(png_const_structrp png_ptr, png_const_inforp info_ptr,
     png_uint_32 flag)
 {
    if (png_ptr != NULL && info_ptr != NULL)
+   {
+#ifdef PNG_READ_tRNS_SUPPORTED
+      /* png_handle_PLTE() may have canceled a valid tRNS chunk but left the
+       * 'valid' flag for the detection of duplicate chunks. Do not report a
+       * valid tRNS chunk in this case.
+       */
+      if (flag == PNG_INFO_tRNS && png_ptr->num_trans == 0)
+         return(0);
+#endif
+
       return(info_ptr->valid & flag);
+   }
 
    return(0);
 }
```

**Comment by wantehchang** [comment]
I attached two PNG images useful for investigating this issue and testing a fix.

Both images are of color type 2 (PNG_COLOR_TYPE_RGB) and have a tRNS chunk and a PLTE chunk. The two images differ only in whether tRNS is before or after PLTE.

Both images have an opaque blue circle on a transparent green background.

circle-trns-before-plte

![circle-trns-before-plte](https://github.com/glennrp/libpng/assets/16024799/f9be928a-46e0-4d1b-aaea-a18a5656448a)

circle-trns-after-plte

![circle-trns-after-plte](https://github.com/glennrp/libpng/assets/16024799/300a1a06-77d4-4eef-a082-b361811f3d8d)

**Comment by wantehchang** [comment]
A workaround, due to Pascal Massimino, is to change the code snippet

```
    if (png_get_valid(png_ptr, info_ptr, PNG_INFO_tRNS))
        png_set_tRNS_to_alpha(png_ptr);
```

to

```
    int num_trans;
    if (png_get_tRNS(png_ptr, info_ptr, NULL, &num_trans, NULL) && num_trans > 0)
        png_set_tRNS_to_alpha(png_ptr);
```

**Comment by ProgramMax** [comment]
Oh, sorry!
Wan-Teh Chang was the person to find this originally. I learned of it from them and wanted to report it here, since I saw it didn't have a bug here yet.

You can Wan-Teh Chang's work here: https://chromium-review.googlesource.com/c/chromium/src/+/4616010

Re-reading my original post, I worry that it could have come across as like I was trying to take credit. Sorry about that. It didn't cross my mind while writing my original post.

Thank you for working on this, Wan-Teh Chang!

**Comment by wantehchang** [comment]
Chris, I really appreciate your writing a good bug report. I was about to report the bug yesterday morning and was happy (and puzzled) to find this bug report written just two hours earlier.

It was Google's internal fuzzing of libwebp2 that found this originally, but I am sure the bug has also been found by other people or fuzzing. Pascal Massimino fixed the libwebp2 fuzzing bug and I learned a lot from his workaround.

Luca Versari, James Zern, and Joe Drago helped me create the test files circle-trns-before-plte.png and circle-trns-after-plte.png.

**Comment by ctruta** [comment]
I acknowledged the author in the AUTHORS file but many thanks to everyone who contributed.

**Comment by jbowler** [comment]
Note that this change seems to break the Chrome check in tests because they apparently check for a tRNS-before-PLTE image returning "true" when tRNS validity is checked.  See PR https://github.com/glennrp/libpng/pull/484

**Comment by jbowler** [comment]
The bottom line is that the logic for all this stuff is not handled in a maintainable way; it's like a recursive descent parser because it is based on lines of code in different places repeating what are effectively the same checks.  The erroneous code here seems to have existing since 1996/7
