### ISSUE TITLE
corrupt png and process aborting/termination

### ISSUE THREAD

**Issue by dinkc64** [glennrp/libpng#497]
Hi,
Are there any plans to make a safer libpng - for example:
if a corrupt png is presented to be decoded, png will try to terminate the process, but if it's a multithreaded app, it ends up crashing instead.  (the stack or heap gets trashed and random functions will either try to run then crash, or, just crash)

This is happening with the current (1.6.40) libpng and current zlib (1.3)

best regards,
- dink

**Comment by jbowler** [comment]
You haven't set the error handler; see the instructions in the header file or, better, use the "simplified" API as described in the header file.

**Comment by ctruta** [comment]
In addition to what @jbowler said, I would like to point out that libpng is safe by design. It shouldn't crash because of a corrupted input file. (And if it does, that would be a bug, which should be reported as such.)
