### ISSUE TITLE
Setting CMake Policy to get rid of Warning when Defining ZLIB_ROOT

### ISSUE THREAD

**Issue by jacobharding** [glennrp/libpng#500]
Hey all first time here :). If you try to build with a version of cmake greater or equal to 3.12 and define ZLIB_ROOT you get this warning:

> CMake Warning (dev) at CMakeLists.txt:98 (find_package):
>   Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
>   Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
>   command to set the policy and suppress this warning.
> 
>   CMake variable ZLIB_ROOT is set to:
> 
>     /Users/path/to/zlib/build
> 
>   For compatibility, CMake is ignoring the variable.
> This warning is for project developers.  Use -Wno-dev to suppress it.

Setting ZLIB_ROOT is a common use case for letting the zlib find module find a specific zlib build first. I think we should set this policy so that its more clear how ZLIB_ROOT will be handled and also at the same time get rid of the warning. 

From what I can tell, cmake versions greater or equal to 3.12 default to the old version of the policy if it isn't explicitly set. The old behaviour of the policy is to ignore \<PackageName\>_ROOT variables when find_package searches for a config file of a package (which libpng and zlib both don't have yet?). In anticipation for zlib providing a cmake package config file and to move away from deprecated behaviour I think we should set the policy to its new behaviour:

`cmake_policy(SET CMP0074 NEW)`

**Comment by ctruta** [comment]
Done. See commit 85f866dea3ca25e95e9ca0e767b90880ec85759d.

> Hey all first time here :)

Bullseye ;-)
