### ISSUE TITLE
Add dll support to command line build for MSVC

### ISSUE THREAD

**Issue by mfeemster** [glennrp/libpng#90]
If I use the visual studio project files I can build libpng.dll

However, if I use the command line like so:

`nmake -f scripts\makefile.vcwin32 all`

It only builds a static libpng.lib

It would be nice to have the option to build it as a .dll with a .lib import library the way the project files do.

Thanks.

**Comment by mancoast** [comment]
Use cmake

**Comment by ctruta** [comment]
`scripts/makefile.*` will be maintained for a little while in "as-is" form, without adding new features. Then they will be gradually discontinued.
